# Generated by Django 4.0.1 on 2022-01-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userapp',
            name='orders',
            field=models.ManyToManyField(blank=True, default=None, related_name='orders_history', to='shopping.Order'),
        ),
    ]
