# Generated by Django 4.0.1 on 2022-01-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_userapp_shopping_cart_alter_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('entertainment', 'Entertainment'), ('books', 'Books')], default='', max_length=20),
        ),
    ]
