# Generated by Django 4.0.1 on 2022-01-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_comment_comment_date_order_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='province',
            field=models.TextField(choices=[('AB', 'ab'), ('BC', 'bc'), ('MB', 'mb'), ('NB', 'nb'), ('NL', 'nl'), ('NS', 'ns'), ('ON', 'on'), ('PE', 'pe'), ('QC', 'Qc'), ('SK', 'sk'), ('NT', 'nt'), ('NU', 'nu'), ('YT', 'yt')]),
        ),
    ]
